# This is a basic workflow to help you get started with Actions

name: Publish Nuget Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: NuGet Installation
        uses: nuget/setup-nuget@v1
        with: 
          nuget-version: "5.2.0"
       
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Restore NuGet Packages
        run: nuget restore LearnToMultiply/LearnToMultiply.csproj
       
      - name: Add Source
        run: nuget sources add -Name "PowelAS" -Source "https://nuget.pkg.github.com/PowelAS/index.json" -username "marcin-rybinski" -password "${{ secrets.NugetKEY }}"
    
      - name: Build
        working-directory: LearnToMultiply
        run:  msbuild LearnToMultiply.csproj /property:Configuration=Release /p:SolutionDir=../
      
      - name: Pack NuGet
        working-directory: LearnToMultiply
        run: nuget pack LearnToMultiply.csproj -Version 1.1.${{ github.run_number }} -Properties Configuration=Release
        
      - name: Publish NuGet
        working-directory: LearnToMultiply
        run: nuget push LearnToMultiply.1.1.${{ github.run_number }}.nupkg -ApiKey ${{ secrets.NugetKEY }} -Source "https://nuget.pkg.github.com/PowelAS/index.json"
